name : Our Workflow
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v4.1.7
        with:
          path: our-source
      - run: ls -al our-source
      - run: cat our-source/.github/workflows/checkoutTest.yml
